'use strict';

module.exports = {
    extends: ['eslint:recommended'],
    rules: {
        'no-template-curly-in-string': 'error',
        'accessor-pairs': 'error',
        'block-scoped-var': 'error',
        curly: ['error', 'multi'],
        'default-case': 'error',
        eqeqeq: 'error',
        'array-callback-return': 'error',
        'no-alert': 'error',
        'no-div-regex': 'error',
        'no-else-return': ['error', { allowElseIf: false }],
        'no-eq-null': 'error',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-floating-decimal': 'error',
        'no-implicit-globals': 'error',
        'no-implied-eval': 'error',
        'no-invalid-this': 'error',
        'no-iterator': 'error',
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        'no-multi-spaces': 'error',
        'no-multi-str': 'error',
        'no-new': 'error',
        'no-new-func': 'error',
        'no-octal-escape': 'error',
        'no-proto': 'error',
        'no-return-assign': 'error',
        'no-self-compare': 'error',
        'no-throw-literal': 'error',
        'no-unmodified-loop-condition': 'error',
        'no-unused-expressions': 'error',
        'no-useless-concat': 'error',
        'prefer-promise-reject-errors': 'warn',
        'vars-on-top': 'error',
        yoda: 'error',
        'no-shadow': 'error',
        'no-undef-init': 'error',
        'no-use-before-define': 'error',
        'no-return-await': 'error',
        'no-param-reassign': 'error',
        'no-implicit-coercion': ['error', { allow: ['!!'] }],
        'array-bracket-newline': ['error', { multiline: true }],
        'array-bracket-spacing': ['error', 'never'],
        'array-element-newline': ['error', { multiline: true }],
        'block-spacing': 'error',
        'brace-style': ['error', '1tbs', { allowSingleLine: true }],
        camelcase: 'error',
        'comma-dangle': ['error', 'never'],
        'comma-spacing': ['error', { before: false, after: true }],
        'comma-style': ['error', 'last'],
        'computed-property-spacing': ['error', 'never'],
        'consistent-this': ['error', '_this'],
        'eol-last': ['error', 'always'],
        'func-call-spacing': ['error', 'never'],
        'func-names': ['error', 'as-needed'],
        'function-paren-newline': ['error', { minItems: 6 }],
        'implicit-arrow-linebreak': ['error', 'beside'],
        indent: ['error', 4],
        'jsx-quotes': ['error', 'prefer-single'],
        'key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
        'keyword-spacing': ['error', { before: true, after: true }],
        'linebreak-style': ['error', 'unix'],
        'lines-around-comment': [
            'error',
            {
                beforeBlockComment: true,
                beforeLineComment: true,
                allowBlockStart: true,
                allowBlockEnd: true,
                allowClassStart: true,
                allowClassEnd: true,
                allowObjectStart: true,
                allowArrayStart: true,
            },
        ],
        'lines-between-class-members': ['error', 'always'],
        'max-depth': ['error', 4],
        'max-len': [
            'error',
            {
                code: 100,
                tabWidth: 4,
                ignoreTemplateLiterals: true,
                ignoreUrls: true,
                ignoreStrings: true,
            },
        ],
        'max-nested-callbacks': ['error', 3],
        'max-params': ['error', 5],
        'max-statements-per-line': ['error', { max: 2 }],
        'multiline-ternary': ['error', 'never'],
        'new-cap': 'error',
        'new-parens': 'error',
        'newline-per-chained-call': ['error', { ignoreChainWithDepth: 2 }],
        'no-array-constructor': 'error',
        'no-bitwise': 'error',
        'no-lonely-if': 'error',
        'no-mixed-operators': 'error',
        'no-multi-assign': 'error',
        'no-multiple-empty-lines': ['error', { max: 5, maxEOF: 1 }],
        'no-new-object': 'error',
        'no-tabs': ['error', { allowIndentationTabs: true }],
        'no-trailing-spaces': ['error', { skipBlankLines: true }],
        'no-unneeded-ternary': 'error',
        'no-whitespace-before-property': 'error',
        'nonblock-statement-body-position': ['error', 'beside'],
        'object-curly-spacing': ['error', 'always'],
        'quote-props': ['error', 'as-needed', { numbers: true }],
        semi: ['error', 'always'],
        'semi-style': ['error', 'last'],
        'space-before-blocks': 'error',
        'space-infix-ops': ['error', { int32Hint: true }],
        'switch-colon-spacing': ['error', { after: true, before: false }],
        'unicode-bom': 'error',
        'arrow-spacing': 'error',
        'no-duplicate-imports': 'error',
        'no-useless-computed-key': 'error',
        'no-useless-constructor': 'error',
        'no-useless-rename': 'error',
        'prefer-rest-params': 'error',
        'prefer-template': 'error',
    },
};
